[package]
name    = "wire-desktop-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[workspace]

[[bin]]
name = "fuzz_interpret_records"
path = "fuzz_targets/fuzz_interpret_records.rs"
test = false
doc  = false

[[bin]]
name = "fuzz_forensic"
path = "fuzz_targets/fuzz_forensic.rs"
test = false
doc  = false

[dependencies]
libfuzzer-sys = "0.4"
wire-desktop-core = { path = "../core" }
wire-desktop-forensic = { path = "../forensic" }
chromium-storage-indexeddb = "0.1"
