
# cargo-vet audits file

[audits]

[[trusted.blob-decoder]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-11"
end = "2027-08-01"

[[trusted.chromium-storage-indexeddb]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-29"
end = "2027-08-06"

[[trusted.forensicnomicon]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-05"
end = "2027-08-06"

[[trusted.forensicnomicon-core]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-28"
end = "2027-08-06"

[[trusted.forensicnomicon-data]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-28"
end = "2027-08-06"

[[trusted.leveldb-core]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-11"
end = "2027-08-01"

[[trusted.protobuf-forensic-core]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-11"
end = "2027-08-01"

[[trusted.safe-read]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-15"
end = "2027-08-06"
